elasticsearch:
  host: http://192.168.199.17:9200/
  setsniff: false
  logstashtype: logs

go:
  apiprefix: /v1/api
  port: 7777
  tokenmaxage: 10800
  env: development
  logdir: 
  tokensecret: AstrRAflaEAA

mysql: 
    dialect: mysql
    database: test
    user: root
    passowrd: 000000
    charset: utf8mb4
    host: 192.168.199.16
    port: 3306
    maxidleconns: 5
    maxopenconns: 10

redis: 
    host: 192.168.199.17
    port: 6379
    passowrd: zhidian
    maxIdle: 3
    maxactive: 5
