elasticsearch:
  host: http://192.168.199.17:9200/
  setsniff: false
  logstashtype: logs

go:
  apiprefix: /v1/api
  port: 7777
  tokenmaxage: 7200
  env: development
  logdir: 

mysql: 
    dialect: mysql
    database: test
    user: root
    passowrd: 000000
    charset: utf8mb4
    host: 192.168.199.17
    port: 3306
    maxidleconns: 5
    maxopenconns: 10

redis: 
    host: 192.168.199.17
    port: 6397
    passowrd: 
    maxIdle: 3
    maxactive: 5